name: Deploy Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Prepare static site
        run: |
          mkdir -p public
          cp -R index.html public/
          # If you have a static assets directory (css/js/img), copy it here
          # cp -R static public/ || true
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
